//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Dato.Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DemoAlquilerGameDBVW : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DemoAlquilerGameDBVW usando la cadena de conexión encontrada en la sección 'DemoAlquilerGameDBVW' del archivo de configuración de la aplicación.
        /// </summary>
        public DemoAlquilerGameDBVW() : base("name=DemoAlquilerGameDBVW", "DemoAlquilerGameDBVW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoAlquilerGameDBVW.
        /// </summary>
        public DemoAlquilerGameDBVW(string connectionString) : base(connectionString, "DemoAlquilerGameDBVW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoAlquilerGameDBVW.
        /// </summary>
        public DemoAlquilerGameDBVW(EntityConnection connection) : base(connection, "DemoAlquilerGameDBVW")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alquiler_Pagado_VW> Alquiler_Pagado_VW_Set
        {
            get
            {
                if ((_Alquiler_Pagado_VW_Set == null))
                {
                    _Alquiler_Pagado_VW_Set = base.CreateObjectSet<Alquiler_Pagado_VW>("Alquiler_Pagado_VW_Set");
                }
                return _Alquiler_Pagado_VW_Set;
            }
        }
        private ObjectSet<Alquiler_Pagado_VW> _Alquiler_Pagado_VW_Set;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alquiler_Por_Pagar_VW> Alquiler_Por_Pagar_VW_Set
        {
            get
            {
                if ((_Alquiler_Por_Pagar_VW_Set == null))
                {
                    _Alquiler_Por_Pagar_VW_Set = base.CreateObjectSet<Alquiler_Por_Pagar_VW>("Alquiler_Por_Pagar_VW_Set");
                }
                return _Alquiler_Por_Pagar_VW_Set;
            }
        }
        private ObjectSet<Alquiler_Por_Pagar_VW> _Alquiler_Por_Pagar_VW_Set;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cantidad_Alquileres_Pagados_VW> Cantidad_Alquileres_Pagados_VW_Set
        {
            get
            {
                if ((_Cantidad_Alquileres_Pagados_VW_Set == null))
                {
                    _Cantidad_Alquileres_Pagados_VW_Set = base.CreateObjectSet<Cantidad_Alquileres_Pagados_VW>("Cantidad_Alquileres_Pagados_VW_Set");
                }
                return _Cantidad_Alquileres_Pagados_VW_Set;
            }
        }
        private ObjectSet<Cantidad_Alquileres_Pagados_VW> _Cantidad_Alquileres_Pagados_VW_Set;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cantidad_Alquileres_Por_Pagar_VW> Cantidad_Alquileres_Por_Pagar_VW_Set
        {
            get
            {
                if ((_Cantidad_Alquileres_Por_Pagar_VW_Set == null))
                {
                    _Cantidad_Alquileres_Por_Pagar_VW_Set = base.CreateObjectSet<Cantidad_Alquileres_Por_Pagar_VW>("Cantidad_Alquileres_Por_Pagar_VW_Set");
                }
                return _Cantidad_Alquileres_Por_Pagar_VW_Set;
            }
        }
        private ObjectSet<Cantidad_Alquileres_Por_Pagar_VW> _Cantidad_Alquileres_Por_Pagar_VW_Set;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto_Descripcion_VW> Producto_Descripcion_VW_Set
        {
            get
            {
                if ((_Producto_Descripcion_VW_Set == null))
                {
                    _Producto_Descripcion_VW_Set = base.CreateObjectSet<Producto_Descripcion_VW>("Producto_Descripcion_VW_Set");
                }
                return _Producto_Descripcion_VW_Set;
            }
        }
        private ObjectSet<Producto_Descripcion_VW> _Producto_Descripcion_VW_Set;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alquiler_Pagado_VW_Set. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlquiler_Pagado_VW_Set(Alquiler_Pagado_VW alquiler_Pagado_VW)
        {
            base.AddObject("Alquiler_Pagado_VW_Set", alquiler_Pagado_VW);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alquiler_Por_Pagar_VW_Set. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlquiler_Por_Pagar_VW_Set(Alquiler_Por_Pagar_VW alquiler_Por_Pagar_VW)
        {
            base.AddObject("Alquiler_Por_Pagar_VW_Set", alquiler_Por_Pagar_VW);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cantidad_Alquileres_Pagados_VW_Set. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCantidad_Alquileres_Pagados_VW_Set(Cantidad_Alquileres_Pagados_VW cantidad_Alquileres_Pagados_VW)
        {
            base.AddObject("Cantidad_Alquileres_Pagados_VW_Set", cantidad_Alquileres_Pagados_VW);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cantidad_Alquileres_Por_Pagar_VW_Set. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCantidad_Alquileres_Por_Pagar_VW_Set(Cantidad_Alquileres_Por_Pagar_VW cantidad_Alquileres_Por_Pagar_VW)
        {
            base.AddObject("Cantidad_Alquileres_Por_Pagar_VW_Set", cantidad_Alquileres_Por_Pagar_VW);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Producto_Descripcion_VW_Set. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProducto_Descripcion_VW_Set(Producto_Descripcion_VW producto_Descripcion_VW)
        {
            base.AddObject("Producto_Descripcion_VW_Set", producto_Descripcion_VW);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameDBVWModel", Name="Alquiler_Pagado_VW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alquiler_Pagado_VW : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alquiler_Pagado_VW.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="producto">Valor inicial de la propiedad Producto.</param>
        /// <param name="fechaDesde">Valor inicial de la propiedad FechaDesde.</param>
        /// <param name="fechaHasta">Valor inicial de la propiedad FechaHasta.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static Alquiler_Pagado_VW CreateAlquiler_Pagado_VW(global::System.Int32 id, global::System.String nombre, global::System.String producto, global::System.DateTime fechaDesde, global::System.DateTime fechaHasta, global::System.Int32 estatus)
        {
            Alquiler_Pagado_VW alquiler_Pagado_VW = new Alquiler_Pagado_VW();
            alquiler_Pagado_VW.ID = id;
            alquiler_Pagado_VW.Nombre = nombre;
            alquiler_Pagado_VW.Producto = producto;
            alquiler_Pagado_VW.FechaDesde = fechaDesde;
            alquiler_Pagado_VW.FechaHasta = fechaHasta;
            alquiler_Pagado_VW.Estatus = estatus;
            return alquiler_Pagado_VW;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                if (_Nombre != value)
                {
                    OnNombreChanging(value);
                    ReportPropertyChanging("Nombre");
                    _Nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nombre");
                    OnNombreChanged();
                }
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                if (_Producto != value)
                {
                    OnProductoChanging(value);
                    ReportPropertyChanging("Producto");
                    _Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Producto");
                    OnProductoChanged();
                }
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaDesde
        {
            get
            {
                return _FechaDesde;
            }
            set
            {
                if (_FechaDesde != value)
                {
                    OnFechaDesdeChanging(value);
                    ReportPropertyChanging("FechaDesde");
                    _FechaDesde = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FechaDesde");
                    OnFechaDesdeChanged();
                }
            }
        }
        private global::System.DateTime _FechaDesde;
        partial void OnFechaDesdeChanging(global::System.DateTime value);
        partial void OnFechaDesdeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHasta
        {
            get
            {
                return _FechaHasta;
            }
            set
            {
                if (_FechaHasta != value)
                {
                    OnFechaHastaChanging(value);
                    ReportPropertyChanging("FechaHasta");
                    _FechaHasta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FechaHasta");
                    OnFechaHastaChanged();
                }
            }
        }
        private global::System.DateTime _FechaHasta;
        partial void OnFechaHastaChanging(global::System.DateTime value);
        partial void OnFechaHastaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoHora
        {
            get
            {
                return _TiempoHora;
            }
            set
            {
                OnTiempoHoraChanging(value);
                ReportPropertyChanging("TiempoHora");
                _TiempoHora = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoHora");
                OnTiempoHoraChanged();
            }
        }
        private global::System.String _TiempoHora;
        partial void OnTiempoHoraChanging(global::System.String value);
        partial void OnTiempoHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoDia
        {
            get
            {
                return _TiempoDia;
            }
            set
            {
                OnTiempoDiaChanging(value);
                ReportPropertyChanging("TiempoDia");
                _TiempoDia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoDia");
                OnTiempoDiaChanged();
            }
        }
        private global::System.String _TiempoDia;
        partial void OnTiempoDiaChanging(global::System.String value);
        partial void OnTiempoDiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoSemana
        {
            get
            {
                return _TiempoSemana;
            }
            set
            {
                OnTiempoSemanaChanging(value);
                ReportPropertyChanging("TiempoSemana");
                _TiempoSemana = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoSemana");
                OnTiempoSemanaChanged();
            }
        }
        private global::System.String _TiempoSemana;
        partial void OnTiempoSemanaChanging(global::System.String value);
        partial void OnTiempoSemanaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioEstimado
        {
            get
            {
                return _PrecioEstimado;
            }
            set
            {
                OnPrecioEstimadoChanging(value);
                ReportPropertyChanging("PrecioEstimado");
                _PrecioEstimado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioEstimado");
                OnPrecioEstimadoChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioEstimado;
        partial void OnPrecioEstimadoChanging(Nullable<global::System.Double> value);
        partial void OnPrecioEstimadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoExento
        {
            get
            {
                return _MontoExento;
            }
            set
            {
                OnMontoExentoChanging(value);
                ReportPropertyChanging("MontoExento");
                _MontoExento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoExento");
                OnMontoExentoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoExento;
        partial void OnMontoExentoChanging(Nullable<global::System.Double> value);
        partial void OnMontoExentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Double> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Double> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoTotal
        {
            get
            {
                return _MontoTotal;
            }
            set
            {
                OnMontoTotalChanging(value);
                ReportPropertyChanging("MontoTotal");
                _MontoTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoTotal");
                OnMontoTotalChanged();
            }
        }
        private Nullable<global::System.Double> _MontoTotal;
        partial void OnMontoTotalChanging(Nullable<global::System.Double> value);
        partial void OnMontoTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                if (_Estatus != value)
                {
                    OnEstatusChanging(value);
                    ReportPropertyChanging("Estatus");
                    _Estatus = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Estatus");
                    OnEstatusChanged();
                }
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameDBVWModel", Name="Alquiler_Por_Pagar_VW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alquiler_Por_Pagar_VW : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alquiler_Por_Pagar_VW.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="producto">Valor inicial de la propiedad Producto.</param>
        /// <param name="fechaDesde">Valor inicial de la propiedad FechaDesde.</param>
        /// <param name="fechaHasta">Valor inicial de la propiedad FechaHasta.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static Alquiler_Por_Pagar_VW CreateAlquiler_Por_Pagar_VW(global::System.Int32 id, global::System.String nombre, global::System.String producto, global::System.DateTime fechaDesde, global::System.DateTime fechaHasta, global::System.Int32 estatus)
        {
            Alquiler_Por_Pagar_VW alquiler_Por_Pagar_VW = new Alquiler_Por_Pagar_VW();
            alquiler_Por_Pagar_VW.ID = id;
            alquiler_Por_Pagar_VW.Nombre = nombre;
            alquiler_Por_Pagar_VW.Producto = producto;
            alquiler_Por_Pagar_VW.FechaDesde = fechaDesde;
            alquiler_Por_Pagar_VW.FechaHasta = fechaHasta;
            alquiler_Por_Pagar_VW.Estatus = estatus;
            return alquiler_Por_Pagar_VW;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                if (_Nombre != value)
                {
                    OnNombreChanging(value);
                    ReportPropertyChanging("Nombre");
                    _Nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nombre");
                    OnNombreChanged();
                }
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                if (_Producto != value)
                {
                    OnProductoChanging(value);
                    ReportPropertyChanging("Producto");
                    _Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Producto");
                    OnProductoChanged();
                }
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaDesde
        {
            get
            {
                return _FechaDesde;
            }
            set
            {
                if (_FechaDesde != value)
                {
                    OnFechaDesdeChanging(value);
                    ReportPropertyChanging("FechaDesde");
                    _FechaDesde = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FechaDesde");
                    OnFechaDesdeChanged();
                }
            }
        }
        private global::System.DateTime _FechaDesde;
        partial void OnFechaDesdeChanging(global::System.DateTime value);
        partial void OnFechaDesdeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHasta
        {
            get
            {
                return _FechaHasta;
            }
            set
            {
                if (_FechaHasta != value)
                {
                    OnFechaHastaChanging(value);
                    ReportPropertyChanging("FechaHasta");
                    _FechaHasta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FechaHasta");
                    OnFechaHastaChanged();
                }
            }
        }
        private global::System.DateTime _FechaHasta;
        partial void OnFechaHastaChanging(global::System.DateTime value);
        partial void OnFechaHastaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoHora
        {
            get
            {
                return _TiempoHora;
            }
            set
            {
                OnTiempoHoraChanging(value);
                ReportPropertyChanging("TiempoHora");
                _TiempoHora = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoHora");
                OnTiempoHoraChanged();
            }
        }
        private global::System.String _TiempoHora;
        partial void OnTiempoHoraChanging(global::System.String value);
        partial void OnTiempoHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoDia
        {
            get
            {
                return _TiempoDia;
            }
            set
            {
                OnTiempoDiaChanging(value);
                ReportPropertyChanging("TiempoDia");
                _TiempoDia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoDia");
                OnTiempoDiaChanged();
            }
        }
        private global::System.String _TiempoDia;
        partial void OnTiempoDiaChanging(global::System.String value);
        partial void OnTiempoDiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoSemana
        {
            get
            {
                return _TiempoSemana;
            }
            set
            {
                OnTiempoSemanaChanging(value);
                ReportPropertyChanging("TiempoSemana");
                _TiempoSemana = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoSemana");
                OnTiempoSemanaChanged();
            }
        }
        private global::System.String _TiempoSemana;
        partial void OnTiempoSemanaChanging(global::System.String value);
        partial void OnTiempoSemanaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioEstimado
        {
            get
            {
                return _PrecioEstimado;
            }
            set
            {
                OnPrecioEstimadoChanging(value);
                ReportPropertyChanging("PrecioEstimado");
                _PrecioEstimado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioEstimado");
                OnPrecioEstimadoChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioEstimado;
        partial void OnPrecioEstimadoChanging(Nullable<global::System.Double> value);
        partial void OnPrecioEstimadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                if (_Estatus != value)
                {
                    OnEstatusChanging(value);
                    ReportPropertyChanging("Estatus");
                    _Estatus = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Estatus");
                    OnEstatusChanged();
                }
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameDBVWModel", Name="Cantidad_Alquileres_Pagados_VW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cantidad_Alquileres_Pagados_VW : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cantidad_Alquileres_Pagados_VW.
        /// </summary>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static Cantidad_Alquileres_Pagados_VW CreateCantidad_Alquileres_Pagados_VW(global::System.Int32 iDCliente, global::System.String nombre, global::System.DateTime fecha, global::System.Int32 estatus)
        {
            Cantidad_Alquileres_Pagados_VW cantidad_Alquileres_Pagados_VW = new Cantidad_Alquileres_Pagados_VW();
            cantidad_Alquileres_Pagados_VW.IDCliente = iDCliente;
            cantidad_Alquileres_Pagados_VW.Nombre = nombre;
            cantidad_Alquileres_Pagados_VW.Fecha = fecha;
            cantidad_Alquileres_Pagados_VW.Estatus = estatus;
            return cantidad_Alquileres_Pagados_VW;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                if (_IDCliente != value)
                {
                    OnIDClienteChanging(value);
                    ReportPropertyChanging("IDCliente");
                    _IDCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCliente");
                    OnIDClienteChanged();
                }
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                if (_Nombre != value)
                {
                    OnNombreChanging(value);
                    ReportPropertyChanging("Nombre");
                    _Nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nombre");
                    OnNombreChanged();
                }
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumAlquiler
        {
            get
            {
                return _NumAlquiler;
            }
            set
            {
                OnNumAlquilerChanging(value);
                ReportPropertyChanging("NumAlquiler");
                _NumAlquiler = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumAlquiler");
                OnNumAlquilerChanged();
            }
        }
        private Nullable<global::System.Int32> _NumAlquiler;
        partial void OnNumAlquilerChanging(Nullable<global::System.Int32> value);
        partial void OnNumAlquilerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                if (_Fecha != value)
                {
                    OnFechaChanging(value);
                    ReportPropertyChanging("Fecha");
                    _Fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Fecha");
                    OnFechaChanged();
                }
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoExento
        {
            get
            {
                return _MontoExento;
            }
            set
            {
                OnMontoExentoChanging(value);
                ReportPropertyChanging("MontoExento");
                _MontoExento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoExento");
                OnMontoExentoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoExento;
        partial void OnMontoExentoChanging(Nullable<global::System.Double> value);
        partial void OnMontoExentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Double> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Double> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoTotal
        {
            get
            {
                return _MontoTotal;
            }
            set
            {
                OnMontoTotalChanging(value);
                ReportPropertyChanging("MontoTotal");
                _MontoTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoTotal");
                OnMontoTotalChanged();
            }
        }
        private Nullable<global::System.Double> _MontoTotal;
        partial void OnMontoTotalChanging(Nullable<global::System.Double> value);
        partial void OnMontoTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                if (_Estatus != value)
                {
                    OnEstatusChanging(value);
                    ReportPropertyChanging("Estatus");
                    _Estatus = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Estatus");
                    OnEstatusChanged();
                }
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameDBVWModel", Name="Cantidad_Alquileres_Por_Pagar_VW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cantidad_Alquileres_Por_Pagar_VW : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cantidad_Alquileres_Por_Pagar_VW.
        /// </summary>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static Cantidad_Alquileres_Por_Pagar_VW CreateCantidad_Alquileres_Por_Pagar_VW(global::System.Int32 iDCliente, global::System.String nombre, global::System.Int32 estatus)
        {
            Cantidad_Alquileres_Por_Pagar_VW cantidad_Alquileres_Por_Pagar_VW = new Cantidad_Alquileres_Por_Pagar_VW();
            cantidad_Alquileres_Por_Pagar_VW.IDCliente = iDCliente;
            cantidad_Alquileres_Por_Pagar_VW.Nombre = nombre;
            cantidad_Alquileres_Por_Pagar_VW.Estatus = estatus;
            return cantidad_Alquileres_Por_Pagar_VW;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                if (_IDCliente != value)
                {
                    OnIDClienteChanging(value);
                    ReportPropertyChanging("IDCliente");
                    _IDCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCliente");
                    OnIDClienteChanged();
                }
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                if (_Nombre != value)
                {
                    OnNombreChanging(value);
                    ReportPropertyChanging("Nombre");
                    _Nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nombre");
                    OnNombreChanged();
                }
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumAlquiler
        {
            get
            {
                return _NumAlquiler;
            }
            set
            {
                OnNumAlquilerChanging(value);
                ReportPropertyChanging("NumAlquiler");
                _NumAlquiler = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumAlquiler");
                OnNumAlquilerChanged();
            }
        }
        private Nullable<global::System.Int32> _NumAlquiler;
        partial void OnNumAlquilerChanging(Nullable<global::System.Int32> value);
        partial void OnNumAlquilerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                if (_Estatus != value)
                {
                    OnEstatusChanging(value);
                    ReportPropertyChanging("Estatus");
                    _Estatus = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Estatus");
                    OnEstatusChanged();
                }
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameDBVWModel", Name="Producto_Descripcion_VW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto_Descripcion_VW : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto_Descripcion_VW.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="producto">Valor inicial de la propiedad Producto.</param>
        public static Producto_Descripcion_VW CreateProducto_Descripcion_VW(global::System.Int32 id, global::System.String codigo, global::System.String producto)
        {
            Producto_Descripcion_VW producto_Descripcion_VW = new Producto_Descripcion_VW();
            producto_Descripcion_VW.ID = id;
            producto_Descripcion_VW.Codigo = codigo;
            producto_Descripcion_VW.Producto = producto;
            return producto_Descripcion_VW;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                if (_Codigo != value)
                {
                    OnCodigoChanging(value);
                    ReportPropertyChanging("Codigo");
                    _Codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Codigo");
                    OnCodigoChanged();
                }
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                if (_Producto != value)
                {
                    OnProductoChanging(value);
                    ReportPropertyChanging("Producto");
                    _Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Producto");
                    OnProductoChanged();
                }
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Categoria
        {
            get
            {
                return _Categoria;
            }
            set
            {
                OnCategoriaChanging(value);
                ReportPropertyChanging("Categoria");
                _Categoria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Categoria");
                OnCategoriaChanged();
            }
        }
        private global::System.String _Categoria;
        partial void OnCategoriaChanging(global::System.String value);
        partial void OnCategoriaChanged();

        #endregion
    
    }

    #endregion
    
}
