//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Cliente", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Cliente), "alquiler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.Alquiler), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Producto", "producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Producto), "alquiler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.Alquiler), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_Alquiler", "alquiler", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Alquiler), "pagoDet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.PagoDetalle), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_PagoCab_Cliente", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Cliente), "pagoCab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.PagoCabecera), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_PagoCab", "pagoCab", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.PagoCabecera), "pagoDet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.PagoDetalle), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Categoria", "categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Categoria), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.Producto), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Marca", "marca", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Marca), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.Producto), true)]
[assembly: EdmRelationshipAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Modelo", "modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Dato.Modelo.Modelo), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Dato.Modelo.Producto), true)]

#endregion

namespace Dato.Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DemoAlquilerGameBD : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DemoAlquilerGameBD usando la cadena de conexión encontrada en la sección 'DemoAlquilerGameBD' del archivo de configuración de la aplicación.
        /// </summary>
        public DemoAlquilerGameBD() : base("name=DemoAlquilerGameBD", "DemoAlquilerGameBD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoAlquilerGameBD.
        /// </summary>
        public DemoAlquilerGameBD(string connectionString) : base(connectionString, "DemoAlquilerGameBD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DemoAlquilerGameBD.
        /// </summary>
        public DemoAlquilerGameBD(EntityConnection connection) : base(connection, "DemoAlquilerGameBD")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alquiler> AlquilerSet
        {
            get
            {
                if ((_AlquilerSet == null))
                {
                    _AlquilerSet = base.CreateObjectSet<Alquiler>("AlquilerSet");
                }
                return _AlquilerSet;
            }
        }
        private ObjectSet<Alquiler> _AlquilerSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> ClienteSet
        {
            get
            {
                if ((_ClienteSet == null))
                {
                    _ClienteSet = base.CreateObjectSet<Cliente>("ClienteSet");
                }
                return _ClienteSet;
            }
        }
        private ObjectSet<Cliente> _ClienteSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Descuento> DescuentoSet
        {
            get
            {
                if ((_DescuentoSet == null))
                {
                    _DescuentoSet = base.CreateObjectSet<Descuento>("DescuentoSet");
                }
                return _DescuentoSet;
            }
        }
        private ObjectSet<Descuento> _DescuentoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PagoCabecera> PagoCabeceraSet
        {
            get
            {
                if ((_PagoCabeceraSet == null))
                {
                    _PagoCabeceraSet = base.CreateObjectSet<PagoCabecera>("PagoCabeceraSet");
                }
                return _PagoCabeceraSet;
            }
        }
        private ObjectSet<PagoCabecera> _PagoCabeceraSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PagoDetalle> PagoDetalleSet
        {
            get
            {
                if ((_PagoDetalleSet == null))
                {
                    _PagoDetalleSet = base.CreateObjectSet<PagoDetalle>("PagoDetalleSet");
                }
                return _PagoDetalleSet;
            }
        }
        private ObjectSet<PagoDetalle> _PagoDetalleSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Precio> PrecioSet
        {
            get
            {
                if ((_PrecioSet == null))
                {
                    _PrecioSet = base.CreateObjectSet<Precio>("PrecioSet");
                }
                return _PrecioSet;
            }
        }
        private ObjectSet<Precio> _PrecioSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> ProductoSet
        {
            get
            {
                if ((_ProductoSet == null))
                {
                    _ProductoSet = base.CreateObjectSet<Producto>("ProductoSet");
                }
                return _ProductoSet;
            }
        }
        private ObjectSet<Producto> _ProductoSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Categoria> CategoriaSet
        {
            get
            {
                if ((_CategoriaSet == null))
                {
                    _CategoriaSet = base.CreateObjectSet<Categoria>("CategoriaSet");
                }
                return _CategoriaSet;
            }
        }
        private ObjectSet<Categoria> _CategoriaSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Marca> MarcaSet
        {
            get
            {
                if ((_MarcaSet == null))
                {
                    _MarcaSet = base.CreateObjectSet<Marca>("MarcaSet");
                }
                return _MarcaSet;
            }
        }
        private ObjectSet<Marca> _MarcaSet;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Modelo> ModeloSet
        {
            get
            {
                if ((_ModeloSet == null))
                {
                    _ModeloSet = base.CreateObjectSet<Modelo>("ModeloSet");
                }
                return _ModeloSet;
            }
        }
        private ObjectSet<Modelo> _ModeloSet;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AlquilerSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlquilerSet(Alquiler alquiler)
        {
            base.AddObject("AlquilerSet", alquiler);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ClienteSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClienteSet(Cliente cliente)
        {
            base.AddObject("ClienteSet", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DescuentoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDescuentoSet(Descuento descuento)
        {
            base.AddObject("DescuentoSet", descuento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PagoCabeceraSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPagoCabeceraSet(PagoCabecera pagoCabecera)
        {
            base.AddObject("PagoCabeceraSet", pagoCabecera);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PagoDetalleSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPagoDetalleSet(PagoDetalle pagoDetalle)
        {
            base.AddObject("PagoDetalleSet", pagoDetalle);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PrecioSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPrecioSet(Precio precio)
        {
            base.AddObject("PrecioSet", precio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProductoSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProductoSet(Producto producto)
        {
            base.AddObject("ProductoSet", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CategoriaSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategoriaSet(Categoria categoria)
        {
            base.AddObject("CategoriaSet", categoria);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MarcaSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMarcaSet(Marca marca)
        {
            base.AddObject("MarcaSet", marca);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ModeloSet. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToModeloSet(Modelo modelo)
        {
            base.AddObject("ModeloSet", modelo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Alquiler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alquiler : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alquiler.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        /// <param name="iDProducto">Valor inicial de la propiedad IDProducto.</param>
        /// <param name="fechaDesde">Valor inicial de la propiedad FechaDesde.</param>
        /// <param name="fechaHasta">Valor inicial de la propiedad FechaHasta.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static Alquiler CreateAlquiler(global::System.Int32 id, global::System.Int32 iDCliente, global::System.Int32 iDProducto, global::System.DateTime fechaDesde, global::System.DateTime fechaHasta, global::System.Int32 estatus)
        {
            Alquiler alquiler = new Alquiler();
            alquiler.ID = id;
            alquiler.IDCliente = iDCliente;
            alquiler.IDProducto = iDProducto;
            alquiler.FechaDesde = fechaDesde;
            alquiler.FechaHasta = fechaHasta;
            alquiler.Estatus = estatus;
            return alquiler;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDProducto
        {
            get
            {
                return _IDProducto;
            }
            set
            {
                OnIDProductoChanging(value);
                ReportPropertyChanging("IDProducto");
                _IDProducto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDProducto");
                OnIDProductoChanged();
            }
        }
        private global::System.Int32 _IDProducto;
        partial void OnIDProductoChanging(global::System.Int32 value);
        partial void OnIDProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaDesde
        {
            get
            {
                return _FechaDesde;
            }
            set
            {
                OnFechaDesdeChanging(value);
                ReportPropertyChanging("FechaDesde");
                _FechaDesde = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaDesde");
                OnFechaDesdeChanged();
            }
        }
        private global::System.DateTime _FechaDesde;
        partial void OnFechaDesdeChanging(global::System.DateTime value);
        partial void OnFechaDesdeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaHasta
        {
            get
            {
                return _FechaHasta;
            }
            set
            {
                OnFechaHastaChanging(value);
                ReportPropertyChanging("FechaHasta");
                _FechaHasta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHasta");
                OnFechaHastaChanged();
            }
        }
        private global::System.DateTime _FechaHasta;
        partial void OnFechaHastaChanging(global::System.DateTime value);
        partial void OnFechaHastaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoHora
        {
            get
            {
                return _TiempoHora;
            }
            set
            {
                OnTiempoHoraChanging(value);
                ReportPropertyChanging("TiempoHora");
                _TiempoHora = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoHora");
                OnTiempoHoraChanged();
            }
        }
        private global::System.String _TiempoHora;
        partial void OnTiempoHoraChanging(global::System.String value);
        partial void OnTiempoHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoDia
        {
            get
            {
                return _TiempoDia;
            }
            set
            {
                OnTiempoDiaChanging(value);
                ReportPropertyChanging("TiempoDia");
                _TiempoDia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoDia");
                OnTiempoDiaChanged();
            }
        }
        private global::System.String _TiempoDia;
        partial void OnTiempoDiaChanging(global::System.String value);
        partial void OnTiempoDiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TiempoSemana
        {
            get
            {
                return _TiempoSemana;
            }
            set
            {
                OnTiempoSemanaChanging(value);
                ReportPropertyChanging("TiempoSemana");
                _TiempoSemana = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TiempoSemana");
                OnTiempoSemanaChanged();
            }
        }
        private global::System.String _TiempoSemana;
        partial void OnTiempoSemanaChanging(global::System.String value);
        partial void OnTiempoSemanaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioEstimado
        {
            get
            {
                return _PrecioEstimado;
            }
            set
            {
                OnPrecioEstimadoChanging(value);
                ReportPropertyChanging("PrecioEstimado");
                _PrecioEstimado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioEstimado");
                OnPrecioEstimadoChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioEstimado;
        partial void OnPrecioEstimadoChanging(Nullable<global::System.Double> value);
        partial void OnPrecioEstimadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Cliente", "cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Producto", "producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "producto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "producto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_Alquiler", "pagoDet")]
        public EntityCollection<PagoDetalle> PagosDetalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoDetalle>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "pagoDet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoDetalle>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "pagoDet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Categoria.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Categoria CreateCategoria(global::System.Int32 id)
        {
            Categoria categoria = new Categoria();
            categoria.ID = id;
            return categoria;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Categoria", "Producto")]
        public EntityCollection<Producto> Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nombre)
        {
            Cliente cliente = new Cliente();
            cliente.ID = id;
            cliente.Nombre = nombre;
            return cliente;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Cliente", "alquiler")]
        public EntityCollection<Alquiler> Alquileres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Alquiler>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "alquiler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Alquiler>("DemoAlquilerGameWinFormModel.FK_Alquiler_Cliente", "alquiler", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoCab_Cliente", "pagoCab")]
        public EntityCollection<PagoCabecera> PagosCabecera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "pagoCab");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "pagoCab", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Descuento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Descuento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Descuento.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Descuento CreateDescuento(global::System.Int32 id)
        {
            Descuento descuento = new Descuento();
            descuento.ID = id;
            return descuento;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PorcentajeDescuento
        {
            get
            {
                return _PorcentajeDescuento;
            }
            set
            {
                OnPorcentajeDescuentoChanging(value);
                ReportPropertyChanging("PorcentajeDescuento");
                _PorcentajeDescuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PorcentajeDescuento");
                OnPorcentajeDescuentoChanged();
            }
        }
        private Nullable<global::System.Double> _PorcentajeDescuento;
        partial void OnPorcentajeDescuentoChanging(Nullable<global::System.Double> value);
        partial void OnPorcentajeDescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Estatus;
        partial void OnEstatusChanging(Nullable<global::System.Int32> value);
        partial void OnEstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Marca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marca : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Marca.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Marca CreateMarca(global::System.Int32 id)
        {
            Marca marca = new Marca();
            marca.ID = id;
            return marca;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Marca", "Producto")]
        public EntityCollection<Producto> Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Modelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modelo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Modelo.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Modelo CreateModelo(global::System.Int32 id)
        {
            Modelo modelo = new Modelo();
            modelo.ID = id;
            return modelo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Modelo", "Producto")]
        public EntityCollection<Producto> Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Producto>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="PagoCabecera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoCabecera : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PagoCabecera.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="iDCliente">Valor inicial de la propiedad IDCliente.</param>
        /// <param name="fecha">Valor inicial de la propiedad Fecha.</param>
        /// <param name="estatus">Valor inicial de la propiedad Estatus.</param>
        public static PagoCabecera CreatePagoCabecera(global::System.Int32 id, global::System.Int32 iDCliente, global::System.DateTime fecha, global::System.Int32 estatus)
        {
            PagoCabecera pagoCabecera = new PagoCabecera();
            pagoCabecera.ID = id;
            pagoCabecera.IDCliente = iDCliente;
            pagoCabecera.Fecha = fecha;
            pagoCabecera.Estatus = estatus;
            return pagoCabecera;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoExento
        {
            get
            {
                return _MontoExento;
            }
            set
            {
                OnMontoExentoChanging(value);
                ReportPropertyChanging("MontoExento");
                _MontoExento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoExento");
                OnMontoExentoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoExento;
        partial void OnMontoExentoChanging(Nullable<global::System.Double> value);
        partial void OnMontoExentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Double> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Double> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoTotal
        {
            get
            {
                return _MontoTotal;
            }
            set
            {
                OnMontoTotalChanging(value);
                ReportPropertyChanging("MontoTotal");
                _MontoTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoTotal");
                OnMontoTotalChanged();
            }
        }
        private Nullable<global::System.Double> _MontoTotal;
        partial void OnMontoTotalChanging(Nullable<global::System.Double> value);
        partial void OnMontoTotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Int32 _Estatus;
        partial void OnEstatusChanging(global::System.Int32 value);
        partial void OnEstatusChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoCab_Cliente", "cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("DemoAlquilerGameWinFormModel.FK_PagoCab_Cliente", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_PagoCab", "pagoDet")]
        public EntityCollection<PagoDetalle> PagosDetalle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoDetalle>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoDet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoDetalle>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoDet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="PagoDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoDetalle : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PagoDetalle.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="iDPagoCab">Valor inicial de la propiedad IDPagoCab.</param>
        /// <param name="iDAlquiler">Valor inicial de la propiedad IDAlquiler.</param>
        public static PagoDetalle CreatePagoDetalle(global::System.Int32 id, global::System.Int32 iDPagoCab, global::System.Int32 iDAlquiler)
        {
            PagoDetalle pagoDetalle = new PagoDetalle();
            pagoDetalle.ID = id;
            pagoDetalle.IDPagoCab = iDPagoCab;
            pagoDetalle.IDAlquiler = iDAlquiler;
            return pagoDetalle;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPagoCab
        {
            get
            {
                return _IDPagoCab;
            }
            set
            {
                OnIDPagoCabChanging(value);
                ReportPropertyChanging("IDPagoCab");
                _IDPagoCab = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPagoCab");
                OnIDPagoCabChanged();
            }
        }
        private global::System.Int32 _IDPagoCab;
        partial void OnIDPagoCabChanging(global::System.Int32 value);
        partial void OnIDPagoCabChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAlquiler
        {
            get
            {
                return _IDAlquiler;
            }
            set
            {
                OnIDAlquilerChanging(value);
                ReportPropertyChanging("IDAlquiler");
                _IDAlquiler = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAlquiler");
                OnIDAlquilerChanged();
            }
        }
        private global::System.Int32 _IDAlquiler;
        partial void OnIDAlquilerChanging(global::System.Int32 value);
        partial void OnIDAlquilerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Double> value);
        partial void OnPrecioUnitarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Double> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Double> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioTotal
        {
            get
            {
                return _PrecioTotal;
            }
            set
            {
                OnPrecioTotalChanging(value);
                ReportPropertyChanging("PrecioTotal");
                _PrecioTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioTotal");
                OnPrecioTotalChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioTotal;
        partial void OnPrecioTotalChanging(Nullable<global::System.Double> value);
        partial void OnPrecioTotalChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_Alquiler", "alquiler")]
        public Alquiler Alquiler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alquiler>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "alquiler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alquiler>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "alquiler").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Alquiler> AlquilerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alquiler>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "alquiler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Alquiler>("DemoAlquilerGameWinFormModel.FK_PagoDet_Alquiler", "alquiler", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_PagoDet_PagoCab", "pagoCab")]
        public PagoCabecera PagoCabecera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoCab").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoCab").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PagoCabecera> PagoCabeceraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoCab");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PagoCabecera>("DemoAlquilerGameWinFormModel.FK_PagoDet_PagoCab", "pagoCab", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Precio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Precio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Precio.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static Precio CreatePrecio(global::System.Int32 id)
        {
            Precio precio = new Precio();
            precio.ID = id;
            return precio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrecioUnitario
        {
            get
            {
                return _PrecioUnitario;
            }
            set
            {
                OnPrecioUnitarioChanging(value);
                ReportPropertyChanging("PrecioUnitario");
                _PrecioUnitario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrecioUnitario");
                OnPrecioUnitarioChanged();
            }
        }
        private Nullable<global::System.Double> _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(Nullable<global::System.Double> value);
        partial void OnPrecioUnitarioChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DemoAlquilerGameWinFormModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        /// <param name="iDMarca">Valor inicial de la propiedad IDMarca.</param>
        /// <param name="iDModelo">Valor inicial de la propiedad IDModelo.</param>
        /// <param name="iDCategoria">Valor inicial de la propiedad IDCategoria.</param>
        public static Producto CreateProducto(global::System.Int32 id, global::System.String codigo, global::System.String descripcion, global::System.Int32 iDMarca, global::System.Int32 iDModelo, global::System.Int32 iDCategoria)
        {
            Producto producto = new Producto();
            producto.ID = id;
            producto.Codigo = codigo;
            producto.Descripcion = descripcion;
            producto.IDMarca = iDMarca;
            producto.IDModelo = iDModelo;
            producto.IDCategoria = iDCategoria;
            return producto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDMarca
        {
            get
            {
                return _IDMarca;
            }
            set
            {
                OnIDMarcaChanging(value);
                ReportPropertyChanging("IDMarca");
                _IDMarca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDMarca");
                OnIDMarcaChanged();
            }
        }
        private global::System.Int32 _IDMarca;
        partial void OnIDMarcaChanging(global::System.Int32 value);
        partial void OnIDMarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDModelo
        {
            get
            {
                return _IDModelo;
            }
            set
            {
                OnIDModeloChanging(value);
                ReportPropertyChanging("IDModelo");
                _IDModelo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDModelo");
                OnIDModeloChanged();
            }
        }
        private global::System.Int32 _IDModelo;
        partial void OnIDModeloChanging(global::System.Int32 value);
        partial void OnIDModeloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCategoria
        {
            get
            {
                return _IDCategoria;
            }
            set
            {
                OnIDCategoriaChanging(value);
                ReportPropertyChanging("IDCategoria");
                _IDCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCategoria");
                OnIDCategoriaChanged();
            }
        }
        private global::System.Int32 _IDCategoria;
        partial void OnIDCategoriaChanging(global::System.Int32 value);
        partial void OnIDCategoriaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Alquiler_Producto", "alquiler")]
        public EntityCollection<Alquiler> Alquileres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Alquiler>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "alquiler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Alquiler>("DemoAlquilerGameWinFormModel.FK_Alquiler_Producto", "alquiler", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Categoria", "categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "categoria").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("DemoAlquilerGameWinFormModel.FK_Producto_Categoria", "categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Marca", "marca")]
        public Marca Marca
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "marca").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "marca").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marca> MarcaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "marca");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marca>("DemoAlquilerGameWinFormModel.FK_Producto_Marca", "marca", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DemoAlquilerGameWinFormModel", "FK_Producto_Modelo", "modelo")]
        public Modelo Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "modelo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "modelo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modelo> ModeloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modelo>("DemoAlquilerGameWinFormModel.FK_Producto_Modelo", "modelo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
